### ISSUE TITLE
云应用版本自动构建更新

### ISSUE THREAD

**Issue by juukee** [Tencent/cloudbase-framework#118]
云应用每次都是手工更新版本，对于自动化集成项目来说缺少功能，希望可以通过增加检测仓库代码提交或者镜像仓库push版本

**Comment by chao** [comment]
这个是可以自己通过jenkins来实现的。

**Comment by binggg** [comment]
可以参考这篇 

https://docs.cloudbase.net/framework/ci.html#1--zhun-bei-gou-jian-huan-jing
