### ISSUE TITLE
如果目录名称中有点的话会导致无法在本地运行云函数

### ISSUE THREAD

**Issue by chao** [Tencent/cloudbase-framework#137]
**Bug 描述**

例如我新建个项目的目录名称叫testing.cloud，那么我在执行云函数的时候就会报错。错误信息见下图。

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/55872/101707488-47f36080-3ac6-11eb-8b93-3e13e2ee6481.png">

只要把目录名称中的点去掉，例如变成testing_cloud就能正常执行。

**Comment by chhpt** [comment]
fixed
