### ISSUE TITLE
希望在cloudbaserc.json文件中能够增加一项云函数的配置，允许这个函数只在本地允许

### ISSUE THREAD

**Issue by chao** [Tencent/cloudbase-framework#138]
**这个功能提议是否涉及到某个问题，请详细描述**

希望在cloudbaserc.json文件中能够增加一项云函数的配置，允许这个函数只在本地允许。我们项目会写一些操作数据库，例如初始数据，迁移数据之类的帮助用途的云函数。这些云函数我们只会在本地运行。希望能通过设置cloudbaserc.json配置这些函数哪怕在`tcb fn deploy --all`的时候也不会被上传到云上。

**Comment by binggg** [comment]
看了下描述，如果只需要本地运行，似乎不需要用云函数的形式，弄一个js文件即可
