### ISSUE TITLE
Framework Function Plugin 不支持配置 公网访问 和 固定出口 IP

### ISSUE THREAD

**Issue by freyo** [Tencent/cloudbase-framework#146]
云函数本身是支持的，面板也能开启，但云函数文档未见相关配置项说明，希望跟进完善CI部署

**Comment by binggg** [comment]
本周会进行支持～～敬请期待

**Comment by freyo** [comment]
> 本周会进行支持～～敬请期待

已经两周了也没支持

**Comment by binggg** [comment]
不好意思，后台发布delay了

**Comment by binggg** [comment]
@freyo 

最新版本已经支持云函数访问公网能力和固定IP的配置

https://github.com/Tencent/cloudbase-framework/blob/master/packages/framework-plugin-function/README.md#functions

![image](https://user-images.githubusercontent.com/7686861/106105738-6e0cb700-617f-11eb-9b22-7b43a451b878.png)
