### ISSUE TITLE
希望nuxt/auth库，支持TCB provider

### ISSUE THREAD

**Issue by DaZiYuan** [Tencent/cloudbase-framework#147]
**请对您遇到问题进行清楚、简洁的描述，比如我遇到一个问题，当我...**
**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**

我想使用nuxt/auth集成tcb的邮箱登录，但不知道如何下手，期待有官方的demo或者provider

**描述您期望的解决方案**
**Describe the solution you'd like**

官方提供provider，支持tcb的各种登录方式。
参考auto0
https://auth.nuxtjs.org/providers/auth0

**请详细描述您预期的效果**  
**A clear and concise description of what you want to happen.**  

直接在nuxt/auth官网，找到tcb模块
![image](https://user-images.githubusercontent.com/80653/103606231-e30a1980-4f50-11eb-8688-a093532e59f5.png)

**您认为可以接受的备选解决方案**
**Describe alternatives you've considered**

出一个tcb集成nuxt/auth的demo也行

**Comment by shenghanqin** [comment]
牛气

**Comment by DaZiYuan** [comment]
也许做成这样，更科学一点
https://firebase.nuxtjs.org/

**Comment by DaZiYuan** [comment]
TCB的登陆鉴权适用于 Nuxt SSR吗，自己研究了一下搞得头大。好像实现不了。。。

**Comment by DaZiYuan** [comment]
TCB 在服务端调用报错 
```
window is not defined
```

希望能给一个nuxt ssr登陆的案例。。。

**Comment by binggg** [comment]
在服务端目前无法实现登录

**Comment by DaZiYuan** [comment]
自己搞好了
