### ISSUE TITLE
提供通用的登录UI，降低门槛，类似于auth0

### ISSUE THREAD

**Issue by DaZiYuan** [Tencent/cloudbase-framework#148]
如果您也有类似的需求，可以这个 issue 下面点赞 👍

也欢迎大家在评论里面详细描述下自己的使用场景和需求
————
**这个功能提议是否涉及到某个问题，请详细描述**
**Is your feature request related to a problem? Please describe. **

tcb现在支持的邮箱登录，账户密码登录，微信登录已经可以满足日常需求，但是使用起来还是有门槛。
希望官方支持出一个包含UI的库，类似于auto0，自带注册，登录界面，开箱即用。

可以参考这个demo：
https://auth0.nuxtjs.org/

![image](https://user-images.githubusercontent.com/80653/103606869-7db72800-4f52-11eb-84f8-b297d338653a.png)
![image](https://user-images.githubusercontent.com/80653/103606747-2add7080-4f52-11eb-9820-4c6710ca0117.png)
![image](https://user-images.githubusercontent.com/80653/103606764-329d1500-4f52-11eb-9a13-b06b6549ff7d.png)

**Comment by shenghanqin** [comment]
牛气

**Comment by simplecooler** [comment]
加一

**Comment by huangjun198604** [comment]
有需要的

**Comment by shenghanqin** [comment]
https://docs.cloudbase.net/cloudbase-ui/authentication.html
这里有了。

**Comment by huangjun198604** [comment]
太感谢！正需要！另外unity sdk出现的不能il2cpp导出bug和修正方法也提交了可以看看~



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月20日(星期天) 下午2:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/cloudbase-framework] 提供通用的登录UI，降低门槛，类似于auth0 (#148)





 
https://docs.cloudbase.net/cloudbase-ui/authentication.html
 这里有了。
