### ISSUE TITLE
如果因为网络等原因部署失败一次，后面就会报：a version is building, please wait for end

### ISSUE THREAD

**Issue by erDaren** [Tencent/cloudbase-framework#150]
**Bug 描述**
**Describe the bug**

网络原因（机场不稳定）部署失败，后面再部署，会提示`a version is building, please wait for end`

**重现步骤**
**To Reproduce**

重现 bug 的步骤：
1. 执行 `yarn deploy:server`
2. 失败后再次执行`yarn deploy:server`
3. 提示`a version is building, please wait for end`

**预期的行为**
**Expected behavior**
前后多次部署行为不会互相影响

**截图**
**Screenshots**
如果方便的话，可以提交截图来帮助我们分析您遇到的问题

**错误日志**
**Debug LOG**
```
[CreateAndDeployCloudBaseProject]
RequestId：***************************
a version is building, please wait for end.
error Command failed with exit code 1.
```

**其他上下文信息**
**Additional context**

**Comment by binggg** [comment]
目前为了保证部署的时候不产生冲突的情况，有设置同一时刻只有同一个版本在发布的限制
遇到这种情况一般超时时间为10min，可以考虑给一个手动cancel 上一个部署的功能

**Comment by noconfuse** [comment]
@binggg 使用tcb framework deplay 部署时如何cancel上一个部署

**Comment by binggg** [comment]
没有支持这个功能，目前只能等待
