### ISSUE TITLE
网站插件支持 cloudbaseenv.js 来获取当前环境下的变量

### ISSUE THREAD

**Issue by binggg** [Tencent/cloudbase-framework#151]
**这个功能提议是否涉及到某个问题，请详细描述**
**Is your feature request related to a problem? Please describe. **

目前网站插件会把变量注入到 /cloudbaseenv.json 中，获取比较麻烦，需要发起异步请求

**描述您期望的解决方案**
**Describe the solution you'd like**

变量双写 cloudbaseenv.js，获取时直接从全局变量中读取，cloudbaseenv.json 继续保留下来用于保存数据。

**其他上下文信息**
**Additional context**

关于这个新功能提议，您可以添加一些上下文信息或者截图信息。

**Comment by wasfzxt** [comment]
支持

**Comment by shenghanqin** [comment]
支持！

**Comment by binggg** [comment]
已经支持

"use": "@cloudbase/framework-plugin-website@1.6.0-alpha.0"

已经支持

文档地址： https://github.com/Tencent/cloudbase-framework/blob/master/packages/framework-plugin-website/README.md#envvariables

![image](https://user-images.githubusercontent.com/7686861/104584851-2a558000-569e-11eb-84cf-c3acae48ee5d.png)
