### ISSUE TITLE
如何在不指定 persistence的情况下，获取用户信息

### ISSUE THREAD

**Issue by DaZiYuan** [Tencent/cloudbase-framework#155]
**这个功能提议是否涉及到某个问题，请详细描述**

我的需求是这样：
- 用户登陆时勾选 “记住我"，采用persistence:"local"，方便用户下次直接使用。
- 不勾选，采用persistence:"session"，关闭浏览器退出登陆。

但是我发现用tcb实现不了这个功能，tcb初始化就必须指定persistence，后面再也不能修改。
如果初始化多个tcb实例也会导致其他问题
```
//测试代码
//例如：使用local登陆后，打开新页面却获取不到用户

            app = cloudbase.init({
                env
            });
            auth = app.auth({ persistence: "local" });
            let r = auth.hasLoginState()
            console.log("test auth", auth, r);

            let app1 = cloudbase.init({
                env
            });
            let auth1 = app1.auth({ persistence: "session" });
            let r1 = auth1.hasLoginState()
            console.log("test auth1", auth1, r1);
```
登陆窗口A 可以获取
![image](https://user-images.githubusercontent.com/80653/104833311-a506e100-58d2-11eb-9abc-9ee09a7c687c.png)

同浏览器，新开的窗口B 无法获取
![image](https://user-images.githubusercontent.com/80653/104833279-5ce7be80-58d2-11eb-99b8-ec3e7a95ab03.png)

**请对您遇到问题进行清楚、简洁的描述，比如我遇到一个问题，当我...**

如何在不指定 persistence的情况下 正确获取用户
```
app.auth();
//persistence: "local" 登陆无法获取
//只要persistence不匹配都获取不了
console.log(app.currentUser);
```

**描述您期望的解决方案**

我并不知道用户是哪种persistence，所以初始化时没办法指定。
指定错了也获取不了。

**请详细描述您预期的效果**

persistence增加 auto类型，默认自动检查。
并且persistence可以在初始化后更改。

**Comment by binggg** [comment]
JSSDK 相关的可以到 https://github.com/TencentCloudBase/cloudbase-js-sdk 这里来提交issue
