### ISSUE TITLE
使用nuxt插件的entry配置后，部署build失败

### ISSUE THREAD

**Issue by manfwh** [Tencent/cloudbase-framework#156]
**Bug 描述**

使用nuxt插件的entry配置后，部署build失败。
`package.json`必须要放在根目录吗?
看到插件源码读取`package.json`的时候都默认是在根目录的
```bash
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path D:\me\project\open\ssr-demo\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'D:\me\project\open\ssr-demo\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

```

**重现步骤**

重现 bug 的步骤：
1. 根目录创建`cloudbaserc.json`文件，使用`@cloudbase/framework-plugin-function`插件，将entry配置为`./nuxt-ssr`
2. 根目录新建nuxt-ssr文件夹，创建nuxt项目
3. 根目录命令行执行`tcb`部署，控制台报错`CloudBase Framework  error     Command failed: npm run build`

**预期的行为**
执行tcb命令后正常部署成功

**截图**
![image](https://user-images.githubusercontent.com/23977810/104836601-eeaef600-58e9-11eb-9e55-8b4e8e623ef2.png)

**Comment by binggg** [comment]
收到，这里应该支持在子目录
