### ISSUE TITLE
framework-plugin-function是否可以支持设置所有函数共用一个环境变量配置

### ISSUE THREAD

**Issue by ldd27** [Tencent/cloudbase-framework#157]
**这个功能提议是否涉及到某个问题，请详细描述**
**Is your feature request related to a problem? Please describe. **

**framework-plugin-function是否可以支持设置所有函数公用一个环境变量配置**

请对您遇到问题进行清楚、简洁的描述，比如我遇到一个问题，当我...

**目前每个函数需要单独设置环境变量，特别是公用函数内引用的环境变量很容易配置漏**

**描述您期望的解决方案**
**Describe the solution you'd like**

**可以支持设置所有函数公用一个环境变量配置**

请详细描述您预期的效果

**可以支持设置所有函数公用一个环境变量配置**

**Comment by binggg** [comment]
已经支持

https://github.com/Tencent/cloudbase-framework/blob/master/packages/framework-plugin-function/README.md#functiondefaultconfig
