### ISSUE TITLE
低版本升级 cloudbase-cli 后导致云函数 API 返回会自动 base64

### ISSUE THREAD

**Issue by biousco** [Tencent/cloudbase-framework#159]
**Bug 描述**
cloudbase-cli 从 1.0.0 升级到最新版 1.2.7 后发布应用导致云函数 API 返回内容会自动 base64

请简单清晰地描述您遇到的bug。
cloudbase-cli 从 1.0.0 升级到最新版 1.2.7 后发布应用导致云函数 API 返回内容会自动 base64

**重现步骤**
**To Reproduce**

重现 bug 的步骤：
1. 准备一个以 cloudbase-cli 1.0 的项目，线上调用云函数返回，内容不会 base64
2. 升级了 cli，cloudbase-freamwork 会自动升级到 1.6.3（原来为 1.0.0）
3. 再次部署项目，云函数的返回内容会自动的 base64 化

**预期的行为**
**Expected behavior**
请简单明了地描述您期望的行为。

**截图**
**Screenshots**
正常 1.0.0 下的应用返回：
<img width="824" alt="企业微信截图_6047b19f-8b72-4b09-8c84-11dc876b9976" src="https://user-images.githubusercontent.com/7815529/105177531-c29daa00-5b61-11eb-95bc-c53b98ef1c3e.png">
升级 cli 后的返回：
<img width="850" alt="企业微信截图_daf5d0c7-8028-4251-9f83-7acff089c0c5" src="https://user-images.githubusercontent.com/7815529/105177579-d3e6b680-5b61-11eb-914c-59b89bb214c5.png">

**错误日志**
**Debug LOG**

请使用 --verbose 参数来打印 debug 日志信息，然后将命令行输出复制在这里

例如 cloudbase framework deploy --verbose

**其他上下文信息**
**Additional context**

**Comment by binggg** [comment]
可以重新升级下，framework 1.6.9 修复了此问题
