### ISSUE TITLE
上传文件超过1000个时，需要人工选择，需要增加一个参数force-yes

### ISSUE THREAD

**Issue by xiaoquqi** [Tencent/cloudbase-framework#168]
使用hosting deploy时，如果上传文件超过1000，会有提示选择是否继续，但是在CI环境中，这就尴尬了，是否增加一个force-yes的参数

这是我在Travis CI中的报错截图

![image](https://user-images.githubusercontent.com/127915/106679318-58701500-65f7-11eb-8e69-38e109eb1918.png)

**Comment by binggg** [comment]
@chhpt 关注下

**Comment by xiaoquqi** [comment]
我是不是提错项目了，应该到cloudbase cli的项目中去提？

**Comment by binggg** [comment]
嗯嗯，这个是CLI 的功能

**Comment by xiaoquqi** [comment]
已经将问题重新提交至sdk项目中

https://github.com/TencentCloudBase/cloudbase-js-sdk/issues/8
