### ISSUE TITLE
Github Actions 建议

### ISSUE THREAD

**Issue by beetcb** [Tencent/cloudbase-framework#184]
使用 cloudbase-framework 部署异常方便，是否可以考虑发布一个 Github Actions 来完善 [cloudbase-action](https://github.com/TencentCloudBase/cloudbase-action) 项目 ? 这样会赋予它管理云开发大部分内容的能力，不仅仅是静态网站发布了

我尝试写了一个 DEMO，效果如下：

![tcb-actions](https://user-images.githubusercontent.com/63141491/108954180-628dac80-76a7-11eb-8960-0fd6ff3609da.png)

[项目地址](https://github.com/beetcb/cloudbase-framework-actions)，如果觉得我的想法还可以，我很愿意提交 PR

**Comment by binggg** [comment]
感谢贡献，我们看下～

**Comment by binggg** [comment]
@beetcb 

我们原来做了一个只可以发布静态托管的github action，可以考虑这个项目的基础上采用你的方案提供一个 V2 版本，基于 cloudbase-framework 来部署完整的项目

https://github.com/TencentCloudBase/cloudbase-action

**Comment by beetcb** [comment]
@binggg 好的，我会在原本的 Actions 项目里贡献。

顺便问一下：
> 我的方案很简单，就10行左右 Shell Script（没有使用 Node 的原因是，几乎所有的逻辑都是使用 NPM 完成的，无需引入 Node，也不需要 Bundler 了），这就与 V1 的逻辑完全冲突了，请问我在提交 PR 的时候如何处理 V1 那部分内容 😊

**Comment by beetcb** [comment]
我本来想过用 Node，那就可以轻松在 actions 里配置插件相关内容

![image](https://user-images.githubusercontent.com/63141491/108974409-6974e900-76c0-11eb-904b-d5f1894c3525.png)

但是说实话，这样写 yml 很麻烦，直接使用 `cloudbaserc.json` 方便多了，可以实现 0 配置

**Comment by binggg** [comment]
V2 可以考虑不用node

**Comment by beetcb** [comment]
云开发 Tencent CloudBase Github Action V2 已就绪 https://github.com/TencentCloudBase/cloudbase-action/pull/18
closing this

**Comment by binggg** [comment]
@all-contributors please add @beetcb  for code

**Comment by TonyWu3027** [comment]
> 我本来想过用 Node，那就可以轻松在 actions 里配置插件相关内容
> 
> ![image](https://user-images.githubusercontent.com/63141491/108975015-020b6900-76c1-11eb-95f3-15bde5095bb6.png)
> 
> 但是说实话，这样写 yml 很麻烦，直接使用 `cloudbaserc.json` 方便多了，可以实现 0 配置

Hi @beetcb and @binggg，目前这套CI解决方案很舒适，非常感谢贡献！

从我的使用经验中我感觉后续版本如果能支持用Actions配置部分甚至完全替代`cloudbaserc.json`的配置项会是一个非常好的feature, 希望能upvote一下这个feature.

## Use Case

我们开发小程序的时候有遇到这么一个用例：`tcb`支持调用`cloudbase-framework-mp`插件来CI/CD小程序，并有两种部署模式：
- `preview` - 打包编译、生成开发版小程序预览二维码
- `upload` - 上传到微信小程序后台，以待升为体验版或提审

现在我们希望写两套workflows，分别监听`dev`和`release`分支。若`dev` on push则`preview` 然后触发webhook actions向IM工具(e.g.飞书 slack 企微)推送预览二维码。若`release` on push则`upload`。日常开发push `dev`触发预览，然后`dev`向`release` PR，merged后触发上传。

但是因为配置层是在`cloudbaserc.json`实现的，因此不支持这种开发流程。可能需要写个脚本去hack一下`cloudbaserc.json`。因此我认为action层可以给用户更多自由度以实现更多可能性

**Comment by binggg** [comment]
可以支持的，cloudbaserc.json 支持环境变量参数来实现动态配置

可以在不同的workflow 中设置不同的环境变量，在cloudbaserc.json 中引用即可实现

参考文档（环境变量既可以通过.env 文件，也可以通过CI里面的环境变量）
https://docs.cloudbase.net/framework/mode.html#mo-ban-bian-liang

**Comment by TonyWu3027** [comment]
Hi @binggg 谢谢回复 可以通过这种方式hack一下 但是像是小程序插件这样的其`preview`和`upload`配置项会有不同，用环境变量可能稍有些麻烦。其实最好的解法我认为是`cloudbase/cli`那边接受一个配置文件路径的参数。

Thanks

**Comment by binggg** [comment]
@TonyWu3027 

嗯嗯，CLI 这里其实是支持的，不过action这里没有支持定制哈，欢迎提个PR哈

 tcb --config-file <path>

**Comment by TonyWu3027** [comment]
@binggg 

okk 我试一下 thanks
