### ISSUE TITLE
framework-plugin-website 插件同步文件缺失

### ISSUE THREAD

**Issue by mxy493** [Tencent/cloudbase-framework#191]
**Bug 描述**

我使用 GitHub Action 将代码仓库同步到腾讯云的静态网站托管，无报错，大部分文件已同步，少数文件没有同步成功。

**重现步骤**
1. 我的 GitHub 仓库：https://github.com/mxy493/mxy493.github.io
2. push 触发 Action 或者手动 Rerun 将仓库文件同步到 腾讯云静态托管，无报错
3. 检查腾讯云静态托管文件夹，路径 `/archieves/page/` 下的所有 `index.html` 文件缺失

Action log：
![image](https://user-images.githubusercontent.com/46776216/110413052-2d7e5280-80c8-11eb-9bcf-560e3eb35386.png)

原仓库：
<img width="941" alt="github" src="https://user-images.githubusercontent.com/46776216/110413300-936ada00-80c8-11eb-9d3d-2846a4dfdd84.png">

静态网站托管相应路径：
<img width="922" alt="cloudbase" src="https://user-images.githubusercontent.com/46776216/110413377-b4cbc600-80c8-11eb-8378-8c17a30d821a.png">

**Comment by zxuqian** [comment]
我也遇到类似情况了，我的网站因为有多语言支持，在 build 之后，会有一个 build/en 目录存放英文版的文件。使用 tcb 部署之后 build/en 下的所有子文件夹（例如 build/en/assets）都是空白。

**Comment by mxy493** [comment]
> 我在本地部署也遇到类似情况了，我的网站因为有多语言支持，在 build 之后，会有一个 build/en 目录存放英文版的文件。使用 tcb 部署之后 build/en 下的所有子文件夹（例如 build/en/assets）都是空白。

![image](https://user-images.githubusercontent.com/46776216/110591341-eb323f80-81b3-11eb-94a2-1f5a5fd0e570.png)

**Comment by zxuqian** [comment]
谢谢！

**Comment by binggg** [comment]
已修复
