### ISSUE TITLE
deploy  不支持yarn ? 

### ISSUE THREAD

**Issue by sytpb** [Tencent/cloudbase-framework#196]
![image](https://user-images.githubusercontent.com/12178686/112804011-7bbeba00-90a6-11eb-9e3f-0bb3bdf4b136.png)

**Comment by sytpb** [comment]
项目是nodejs + express  包管理器是yarn ， deplay 时报上面的错误， 与技术支持沟通后得到答复是不支持yarn , 有点犯难了，项目之前是从npm 升级改用yarn , 这可咋整 。。。。 ？

**Comment by binggg** [comment]
这是安装插件失败了，跟项目的依赖管理没关系，可以重试下看看

**Comment by sytpb** [comment]
果然是，npm cache clean --force  又试了几次成功了  ，但是访问报错了 
`返回结果：

{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /var/user/node_modules/ref-napi/prebuilds/linux-x64/node.napi.node)\n    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)\n    at Module.load (internal/modules/cjs/loader.js:600:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:531:3)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at load (/var/user/node_modules/node-gyp-build/index.js:21:10)\n    at Object.\u003canonymous\u003e (/var/user/node_modules/ref-napi/lib/ref.js:8:53)\n    at Module._compile (internal/modules/cjs/loader.js:701:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)","statusCode":430}`

**Comment by binggg** [comment]
看起来似乎是有些npm模块在云函数中不支持，可以考虑用云托管的方式部署

**Comment by sytpb** [comment]
哈哈 最怕部署了，执行得花不少时间，  行，我看看托管怎么改，重新来。：）

**Comment by sytpb** [comment]
deploy 前，我把前端代码已经放进服务端代码一起 ，public /build     部署成功的话，应用里，点访问，正常的话是不是能打开网站。。？

**Comment by sytpb** [comment]
![image](https://user-images.githubusercontent.com/12178686/112832026-52625600-90c7-11eb-90ce-26b49cb61188.png)
![image](https://user-images.githubusercontent.com/12178686/112832039-57bfa080-90c7-11eb-97ac-6c3a329da8aa.png)
改成 云托管后。报错

**Comment by binggg** [comment]
@sytpb 是否已经成功了，这边查看日志没有报错

**Comment by sytpb** [comment]
部署成功了，但是访问出错，不知道如何排查？

**Comment by sytpb** [comment]
![image](https://user-images.githubusercontent.com/12178686/112970264-97968e80-9180-11eb-9200-701793b98e49.png)

**Comment by sytpb** [comment]
请问一下用node 插件如何配置我的静态网页的路径， 打包好的web文件放到了./public/build 下。  ？？？

**Comment by binggg** [comment]
> 请问一下用node 插件如何配置我的静态网页的路径， 打包好的web文件放到了./public/build 下。 ？？？

@sytpb 这个是根据你的node 应用框架来的
