### ISSUE TITLE
TypeError: app.listen is not a function

### ISSUE THREAD

**Issue by sytpb** [Tencent/cloudbase-framework#207]
cloudbase framework deploy  一个node 程序

一个很简单后台的程序，不是网站后台服务， 一个单独轮询数据库的程序。 

部署时，报错

arksentry-001 2021-04-14T06:29:12.658459504Z stdout F Wed Apr 14 2021 06:29:12 GMT+0000 (Coordinated Universal Time) Sentry service start
larksentry-001 2021-04-14T06:29:12.672777685Z stderr F (node:1) UnhandledPromiseRejectionWarning: TypeError: app.listen is not a function
larksentry-001 2021-04-14T06:29:12.672811009Z stderr F at /usr/src/app/__launcher.js:12:7
larksentry-001 2021-04-14T06:29:12.67281616Z stderr F at Object.<anonymous> (/usr/src/app/__launcher.js:13:3)
larksentry-001 2021-04-14T06:29:12.672820011Z stderr F at Module._compile (internal/modules/cjs/loader.js:778:30)
larksentry-001 2021-04-14T06:29:12.672823589Z stderr F at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
larksentry-001 2021-04-14T06:29:12.672827368Z stderr F at Module.load (internal/modules/cjs/loader.js:653:32)
larksentry-001 2021-04-14T06:29:12.672830831Z stderr F at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
larksentry-001 2021-04-14T06:29:12.672834251Z stderr F at Function.Module._load (internal/modules/cjs/loader.js:585:3)
larksentry-001 2021-04-14T06:29:12.672838079Z stderr F at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
larksentry-001 2021-04-14T06:29:12.672841637Z stderr F at startup (internal/bootstrap/node.js:283:19)
larksentry-001 2021-04-14T06:29:12.672845851Z stderr F at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by binggg** [comment]
@sytpb 

https://docs.cloudbase.net/framework/plugins/framework-plugin-node.html#entry

可以检查下是否有正常导出 app
