### ISSUE TITLE
Unity插件不能用IL2CPP导出

### ISSUE THREAD

**Issue by huangjun198604** [Tencent/cloudbase-framework#222]
Unity插件不能用IL2CPP导出，
是newtonsoft这个东西的配置导致的，
建议学习json.net for unity，
配置一个xml就可以各个平台使用il2cpp导出了，
这个bug严重限制了tcb在vr里的使用，
望修复

**Comment by Mrjing** [comment]
unity插件目前开源了，建议可以提 pr 贡献哈
