### ISSUE TITLE
部署VuePress无法成功

### ISSUE THREAD

**Issue by duan-1** [Tencent/cloudbase-framework#247]
按照 Vuepress 的官方部署指南、ClouBase 的官方指南以及 tcb 命令按照提示，从本地部署上CloudBase都报同一个错误：

CloudBase CloudBase Framework::error  Cannot glob \`**,!.git,!.github,!node_modules,!cloudbaserc.js\`: ENOENT: no such file or directory, stat 'E:\project\xxx\.vuepress\dist'

看日志 **cloudbaser.js** 处标蓝，不知道是不是高亮问题，标为蓝色。
多方查阅，同时把 Issues 都看了一遍，没有发现有帮助的信息，就提交了这个 issue。

**Comment by binggg** [comment]
可以检查下 'E:\project\xxx.vuepress\dist'这个目录是否存在



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月1日(周五) 晚上7:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Tencent/cloudbase-framework] 部署VuePress无法成功 (Issue #247)




 
按照 Vuepress 的官方部署指南、ClouBase 的官方指南以及 tcb 命令按照提示，从本地部署上CloudBase都报同一个错误：
 
CloudBase CloudBase Framework::error  Cannot glob `**,!.git,!.github,!node_modules,!cloudbaserc.js`: ENOENT: no such file or directory, stat 'E:\project\xxx.vuepress\dist'
 
看日志 cloudbaser.js 处标蓝，不知道是不是高亮问题，标为蓝色。
 多方查阅，同时把 Issues 都看了一遍，没有发现有帮助的信息，就提交了这个 issue。

**Comment by Atliyasi** [comment]
请问一下解决了吗。2年后同样遇到了这个问题T^T，目录啥的都存在着，自己编译没有问题用来tcb就会保这个错误

**Comment by duan-1** [comment]
> 请问一下解决了吗。2年后同样遇到了这个问题T^T，目录啥的都存在着，自己编译没有问题用来tcb就会保这个错误

非常可惜，在当年尝试多次未成功就弃用了

**Comment by Atliyasi** [comment]
我找到了解决方法，这个实际上检测的是cloudbaserc.json这个文件中的outputPath这个路径。
![image](https://chdclouds.com:1236/oss/chx-test/777347474eb14ba1e7b2bfa262a3e85e)
这个路径是否存在，是会不会引起报错的关键。
