### ISSUE TITLE
配置选项完善

### ISSUE THREAD

**Issue by juukee** [Tencent/cloudbase-framework#76]
配置选项中希望增加**备注配置**，**日志采集配置**，与官方控制台配置选项保持一致..

**Comment by websmallrabbit** [comment]
Error: 网站托管当前只能部署到按量付费的环境下，请先在控制台切换计费方式

**Comment by websmallrabbit** [comment]
Error: 网站托管当前只能部署到按量付费的环境下，请先在控制台切换计费方式 部署时出现这个错误

**Comment by binggg** [comment]
@websmallrabbit 可以换一个按量计费的环境来部署

**Comment by binggg** [comment]
1.4.0 版本支持

**Comment by binggg** [comment]
已经支持
